# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.proto import neurogrid_pb2 as neurogrid__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in neurogrid_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedAggregatorStub(object):
    """FederatedAggregator serves both the District tier (receives building Δθ
    uploads) and the City tier (receives district summaries). The same RPC
    surface is sufficient because both tiers run the same FedAvg / Krum loop -
    only the parent address differs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendGradient = channel.unary_unary(
                '/neurogrid.FederatedAggregator/SendGradient',
                request_serializer=neurogrid__pb2.WeightPayload.SerializeToString,
                response_deserializer=neurogrid__pb2.AckResponse.FromString,
                _registered_method=True)
        self.PollDistillation = channel.unary_unary(
                '/neurogrid.FederatedAggregator/PollDistillation',
                request_serializer=neurogrid__pb2.PollRequest.SerializeToString,
                response_deserializer=neurogrid__pb2.DistilledModel.FromString,
                _registered_method=True)


class FederatedAggregatorServicer(object):
    """FederatedAggregator serves both the District tier (receives building Δθ
    uploads) and the City tier (receives district summaries). The same RPC
    surface is sufficient because both tiers run the same FedAvg / Krum loop -
    only the parent address differs.
    """

    def SendGradient(self, request, context):
        """Children push Δθ uplink (Building → District, District → City).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollDistillation(self, request, context):
        """Children poll for the freshest distilled / aggregated parent model W*.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedAggregatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendGradient': grpc.unary_unary_rpc_method_handler(
                    servicer.SendGradient,
                    request_deserializer=neurogrid__pb2.WeightPayload.FromString,
                    response_serializer=neurogrid__pb2.AckResponse.SerializeToString,
            ),
            'PollDistillation': grpc.unary_unary_rpc_method_handler(
                    servicer.PollDistillation,
                    request_deserializer=neurogrid__pb2.PollRequest.FromString,
                    response_serializer=neurogrid__pb2.DistilledModel.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neurogrid.FederatedAggregator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neurogrid.FederatedAggregator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedAggregator(object):
    """FederatedAggregator serves both the District tier (receives building Δθ
    uploads) and the City tier (receives district summaries). The same RPC
    surface is sufficient because both tiers run the same FedAvg / Krum loop -
    only the parent address differs.
    """

    @staticmethod
    def SendGradient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neurogrid.FederatedAggregator/SendGradient',
            neurogrid__pb2.WeightPayload.SerializeToString,
            neurogrid__pb2.AckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollDistillation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neurogrid.FederatedAggregator/PollDistillation',
            neurogrid__pb2.PollRequest.SerializeToString,
            neurogrid__pb2.DistilledModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
