# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: neurogrid.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'neurogrid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fneurogrid.proto\x12\tneurogrid\"k\n\rWeightPayload\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x18\n\x10state_dict_bytes\x18\x03 \x01(\x0c\x12\x11\n\tn_samples\x18\x04 \x01(\x05\x12\x0c\n\x04tier\x18\x05 \x01(\t\">\n\x0b\x41\x63kResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05round\x18\x03 \x01(\x05\"6\n\x0bPollRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x15\n\rcurrent_round\x18\x02 \x01(\x05\"_\n\x0e\x44istilledModel\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\r\n\x05round\x18\x02 \x01(\x05\x12\x18\n\x10state_dict_bytes\x18\x03 \x01(\x0c\x12\x11\n\tconverged\x18\x04 \x01(\x08\x32\xa2\x01\n\x13\x46\x65\x64\x65ratedAggregator\x12\x42\n\x0cSendGradient\x12\x18.neurogrid.WeightPayload\x1a\x16.neurogrid.AckResponse\"\x00\x12G\n\x10PollDistillation\x12\x16.neurogrid.PollRequest\x1a\x19.neurogrid.DistilledModel\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'neurogrid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEIGHTPAYLOAD']._serialized_start=30
  _globals['_WEIGHTPAYLOAD']._serialized_end=137
  _globals['_ACKRESPONSE']._serialized_start=139
  _globals['_ACKRESPONSE']._serialized_end=201
  _globals['_POLLREQUEST']._serialized_start=203
  _globals['_POLLREQUEST']._serialized_end=257
  _globals['_DISTILLEDMODEL']._serialized_start=259
  _globals['_DISTILLEDMODEL']._serialized_end=354
  _globals['_FEDERATEDAGGREGATOR']._serialized_start=357
  _globals['_FEDERATEDAGGREGATOR']._serialized_end=519
# @@protoc_insertion_point(module_scope)
